[package]
name = "crypt_guard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.8"
crypt_guard = "1.2.13"
hex = "0.4.3"
