name: Rust

on:
  push:
    branches: [ "Stable" ]
  pull_request:
    branches: [ "Stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
